env:
  global:
    - CC_TEST_REPORTER_ID=6e6dcba8a8cdf32cad8ce638e04bbd20b59d20fa02609095307eec3564e40344
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
services:
  - mysql
install:
  - "sudo apt install gcc"
  - "sudo apt install protobuf-compiler"
  - "pip install -r requirements.txt"
  - "pip install coverage"
# command to run tests
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - "python setup.py install"
  - "python setup.py test"
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
