env:
  global:
    - CODECLIMATE_REPO_TOKEN=6e6dcba8a8cdf32cad8ce638e04bbd20b59d20fa02609095307eec3564e40344
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
services:
  - mysql
install:
  - "sudo apt install gcc"
  - "sudo apt install protobuf-compiler"
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install codeclimate-test-reporter"
# command to run tests
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
script:
  - "python setup.py install"
  - "python setup.py test"
after-success:
  - "codeclimate-test-reporter"
